In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd

In [64]:
def get_listings(page):
    
    cookies = {
        'huntr_referrer': '',
        '__client_uat': '0',
        'mp_1d6f823f8d5432354b55fc0af879343c_mixpanel': '%7B%22distinct_id%22%3A%20%22%24device%3A191222c55ee1d1d-0a7a9200776677-26001e51-11a2a6-191222c55ef1d1d%22%2C%22%24device_id%22%3A%20%22191222c55ee1d1d-0a7a9200776677-26001e51-11a2a6-191222c55ef1d1d%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22__mps%22%3A%20%7B%7D%2C%22__mpso%22%3A%20%7B%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D%2C%22__mpus%22%3A%20%7B%7D%2C%22__mpa%22%3A%20%7B%7D%2C%22__mpu%22%3A%20%7B%7D%2C%22__mpr%22%3A%20%5B%5D%2C%22__mpap%22%3A%20%5B%5D%7D',
    }

    headers = {
        'accept': 'application/json, text/plain, */*',
        'accept-language': 'en-US,en;q=0.5',
        # 'cookie': 'huntr_referrer=; __client_uat=0; mp_1d6f823f8d5432354b55fc0af879343c_mixpanel=%7B%22distinct_id%22%3A%20%22%24device%3A191222c55ee1d1d-0a7a9200776677-26001e51-11a2a6-191222c55ef1d1d%22%2C%22%24device_id%22%3A%20%22191222c55ee1d1d-0a7a9200776677-26001e51-11a2a6-191222c55ef1d1d%22%2C%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%2C%22__mps%22%3A%20%7B%7D%2C%22__mpso%22%3A%20%7B%22%24initial_referrer%22%3A%20%22%24direct%22%2C%22%24initial_referring_domain%22%3A%20%22%24direct%22%7D%2C%22__mpus%22%3A%20%7B%7D%2C%22__mpa%22%3A%20%7B%7D%2C%22__mpu%22%3A%20%7B%7D%2C%22__mpr%22%3A%20%5B%5D%2C%22__mpap%22%3A%20%5B%5D%7D',
        'priority': 'u=1, i',
        'referer': 'https://huntr.co/jobs',
        'sec-ch-ua': '"Not)A;Brand";v="99", "Brave";v="127", "Chromium";v="127"',
        'sec-ch-ua-mobile': '?0',
        'sec-ch-ua-platform': '"Windows"',
        'sec-fetch-dest': 'empty',
        'sec-fetch-mode': 'cors',
        'sec-fetch-site': 'same-origin',
        'sec-gpc': '1',
        'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
    }
    
    params = {
        'page': str(page)
    }
    
    response = requests.get('https://huntr.co/public/search/job-posts', params=params, cookies=cookies, headers=headers)
    json_response = response.json()
    master_list = []
    
    for listing in json_response["results"]:
        try:
            data_dict = {}
            data_dict["id"] = listing["id"]
            data_dict["createdAt"] = listing["createdAt"]
            data_dict["remote"] = listing["isRemote"]
            data_dict["employeeCount"] = listing["employeeCount"]
            data_dict["originalTitle"] = listing["originalTitle"]
            #data_dict["places"] = listing["places"]
            data_dict["place_name"] = listing["places"][0]["name"]
            data_dict["address"] = listing["places"][0]["address"]
            data_dict["country"] = listing["places"][0]["country"]
        except:
            data_dict["id"] = ""
            data_dict["createdAt"] = ""
            data_dict["remote"] = ""
            data_dict["employeeCount"] = ""
            data_dict["originalTitle"] = ""
            #data_dict["places"] = ""
            data_dict["place_name"] = ""
            data_dict["address"] = ""
            data_dict["country"] = ""
        master_list.append(data_dict)
    df = pd.DataFrame(master_list)
    return df

In [ ]:
for i in range(10):
    listings = get_listings(i+1)
    listing.to_csv('page_' + str(i + 1) + '.csv', index = False)

In [69]:
listings

,id,createdAt,remote,employeeCount,originalTitle,place_name,address,country
0,66ac54d0d39dc1004caaf13f,2024-08-02T03:38:56.361Z,False,1664,"Executive Director, Technology Sales",USA,USA,USA
1,66ac54ccf5990a005b4883be,2024-08-02T03:38:52.730Z,False,1664,Clinical Content Coordinator,"Atlanta, Fulton County, Georgia, USA","Atlanta, Fulton County, Georgia, USA",United States of America
2,66ac54cb2881f1005299365d,2024-08-02T03:38:51.839Z,False,1664,"Digital Content Strategist, Campaigns","El Segundo, California, 90245, USA","El Segundo, California, 90245, USA",United States of America
3,66ac54c4210dc90054c7b344,2024-08-02T03:38:44.409Z,False,1664,Project Manager,"London, Greater London, England, SW1A 2DX, Uni...","London, Greater London, England, SW1A 2DX, Uni...",United Kingdom
4,66ac54a2210dc90054c7b2c1,2024-08-02T03:38:10.463Z,False,1664,Market Research Specialist,"Newark, Essex County, New Jersey, USA","Newark, Essex County, New Jersey, USA",United States of America
5,66ac5478f5990a005b4882ec,2024-08-02T03:37:28.111Z,False,1664,Associate Email Marketing Producer,"Navi Mumbai, Thane, Maharashtra, 400706, India","Navi Mumbai, Thane, Maharashtra, 400706, India",India
6,66ac5475d39dc1004caaf029,2024-08-02T03:37:25.647Z,False,607,"Manager, Partner Development","New York, New York, USA","New York, New York, USA",United States of America
7,66ac5471f5990a005b488242,2024-08-02T03:37:21.168Z,False,1664,Quality Assurance Analyst,Ho Chi Minh City,"Ho Chi Minh City, Vietnam",Vietnam
8,66ac546fd39dc1004caaefb7,2024-08-02T03:37:19.994Z,False,1664,Program Manager,"Atlanta, Fulton County, Georgia, USA","Atlanta, Fulton County, Georgia, USA",United States of America
9,66ac546df5990a005b4881d2,2024-08-02T03:37:17.686Z,False,1664,"Associate Director, Marketing","Newark, Essex County, New Jersey, USA","Newark, Essex County, New Jersey, USA",United States of America
10,66ac545b210dc90054c7b201,2024-08-02T03:36:59.673Z,False,1664,Product Program Manager,"Madison, Dane County, Wisconsin, USA","Madison, Dane County, Wisconsin, USA",United States of America
11,66ac545a210dc90054c7b199,2024-08-02T03:36:58.231Z,False,1664,Editorial Director,USA,USA,USA
12,66ac5458210dc90054c7b11f,2024-08-02T03:36:56.127Z,False,1664,Account Manager,USA,USA,USA
13,66ac5457d39dc1004caaef1b,2024-08-02T03:36:55.610Z,False,1664,Lead Security Engineer,"Newark, Essex County, New Jersey, USA","Newark, Essex County, New Jersey, USA",United States of America
14,66ac5454210dc90054c7b0bd,2024-08-02T03:36:52.286Z,False,1664,Programmatic Campaign Manager,"Madison, Dane County, Wisconsin, USA","Madison, Dane County, Wisconsin, USA",United States of America
15,66ac54534cb206006343fce5,2024-08-02T03:36:51.997Z,False,1664,Compliance Analyst,"Portland, Multnomah County, Oregon, USA","Portland, Multnomah County, Oregon, USA",United States of America
16,66ac54532881f100529934b3,2024-08-02T03:36:51.702Z,False,1664,Contracts Administrator/Paralegal,"Newark, Essex County, New Jersey, USA","Newark, Essex County, New Jersey, USA",United States of America
17,66ac544cf5990a005b48814f,2024-08-02T03:36:44.944Z,False,1664,"Manager, Account Management",USA,USA,USA
18,66ac541d4cb206006343fc40,2024-08-02T03:35:57.141Z,False,1664,"Senior Well-Being Program Manager (Austin, Texas)",USA,USA,USA
19,66ac5409f5990a005b4880a5,2024-08-02T03:35:37.425Z,False,1664,Data Engineer,"Portland, Multnomah County, Oregon, USA","Portland, Multnomah County, Oregon, USA",United States of America
20,66ac53e0210dc90054c7afd9,2024-08-02T03:34:56.695Z,False,1664,Digital Marketing Specialist,"Atlanta, Fulton County, Georgia, USA","Atlanta, Fulton County, Georgia, USA",United States of America
21,66ac53ccd39dc1004caaee3e,2024-08-02T03:34:36.062Z,False,1664,Account Manager,Belgium,Belgium,Belgium
22,66ac53c6f5990a005b488005,2024-08-02T03:34:30.513Z,False,1664,"Director, Strategic Accounts",USA,USA,USA
23,66ac53c3210dc90054c7af15,2024-08-02T03:34:27.807Z,False,1664,Account Associate,USA,USA,USA
24,66ac52cfd39dc1004caaec86,2024-08-02T03:30:23.714Z,False,1664,Program Marketing Manager,"London, Greater London, England, SW1A 2DX, Uni...","London, Greater London, England, SW1A 2DX, Uni...",United Kingdom
25,66ac527e4cb206006343f949,2024-08-02T03:29:02.841Z,False,1664,Email Marketing Producer,"Navi Mumbai, Thane, Maharashtra, 400706, India","Navi Mumbai, Thane, Maharashtra, 400706, India",India
26,66ac5270f5990a005b487e1e,2024-08-02T03:28:48.862Z,False,1664,Associate Marketing Manager,"Newark, Essex County, New Jersey, USA","Newark, Essex County, New Jersey, USA",United States of America
27,66ac52632881f100529931d1,2024-08-02T03:28:35.093Z,False,1664,Lead Medical Writing,"Konstanz, Konstanz, Baden-Württemberg, Germany","Konstanz, Konstanz, Baden-Württemberg, Germany",Germany
28,66ac5219d39dc1004caaea4c,2024-08-02T03:27:21.542Z,False,1664,"Director, Strategic Accounts",USA,USA,USA
29,66ac520fd39dc1004caae9bc,2024-08-02T03:27:11.876Z,False,1664,Part Time Well-being Program Manager (Martinez...,USA,USA,USA

In [ ]:
listing.to_csv('page_' + (listing + 1) + '.csv', index = False)